### ISSUE TITLE
barryvdh/laravel-debugbar is now on version 2

### ISSUE THREAD

**Issue by jbibbs** [Flynsarmy/oc-debugbar-plugin#4]
The composer file needs updated to require: "barryvdh/laravel-debugbar": "2.*" for compatibility with the October master branch, and the switch to Laravel 5.

**Comment by Flynsarmy** [comment]
I don't really plan on supporting this plugin as it has issues with overriding October's version of laravel with the one pulled in from debugbar. If you send a PR i'll accept though.

**Comment by jbibbs** [comment]
Nah, I'll just close the issue. Thanks for the heads up.
